server:
  # 端口
  port: 8200

spring:
  application:
    # 别名
    name: rest-service2
eureka:
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://49.233.23.156:8000/eureka/
# 熔断器
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000 # 设置hystrix的超时时间为9000ms
      circuitBreaker:
        requestVolumeThreshold: 5 # 10秒种访问5次都失败的话, 会断开服务,不调用方法,直接进入fallback
        sleepWindowInMilliseconds : 5000 # 默认是5秒 5秒后尝试再访问一次服务器
# 熔断器仪表盘
management:
  endpoints:
    web:
      exposure:
        include: "*"