# 当前服务端口
server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    registerWithEureka: false
    # 表示表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    fetchRegistry: false
    # 注册中心也是 eureka client，所以也需要声明注册地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/